//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÄlytaloMVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talo()
        {
            this.Sauna = new HashSet<Sauna>();
            this.Valo = new HashSet<Valo>();
        }
    
        public int TaloId { get; set; }
        public string Nimi { get; set; }
        public Nullable<int> Lampotila { get; set; }
        public Nullable<int> TavoiteLampotila { get; set; }
        public Nullable<System.DateTime> Paivitetty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sauna> Sauna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valo> Valo { get; set; }
    }
}
