//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÄlytaloMVC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valo
    {
        public int ValoId { get; set; }
        public string Nimi { get; set; }
        public string ValonTila { get; set; }
        public Nullable<int> Valonmaara { get; set; }
        public Nullable<System.DateTime> Paivitetty { get; set; }
        public Nullable<int> TaloId { get; set; }
    
        public virtual Talo Talo { get; set; }
    }
}
